-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 18, 2024 at 03:50 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `clients`
--
CREATE DATABASE IF NOT EXISTS `clients` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `clients`;

-- --------------------------------------------------------

--
-- Table structure for table `courses`
--

CREATE TABLE `courses` (
  `Course_ID` int(13) NOT NULL,
  `CourseTitle` varchar(255) NOT NULL,
  `Price` int(13) NOT NULL,
  `Instructor` varchar(255) NOT NULL,
  `Date` date NOT NULL,
  `Duration` varchar(255) NOT NULL,
  `Description` varchar(255) NOT NULL,
  `More_Details` varchar(1300) NOT NULL,
  `Image` varchar(255) NOT NULL,
  `videoLink` varchar(255) NOT NULL,
  `Category` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `courses`
--

INSERT INTO `courses` (`Course_ID`, `CourseTitle`, `Price`, `Instructor`, `Date`, `Duration`, `Description`, `More_Details`, `Image`, `videoLink`, `Category`) VALUES
(1, 'Introduction to Python Programming', 100, 'John Smith', '2024-09-28', '2 Weeks', 'Learn the basics of Python, including syntax, functions, and more.', 'This \"Introduction to Python Programming\" course covers the fundamental concepts of Python,<br> guiding you through everything from basic syntax to more advanced programming techniques.<br> You\'ll learn Python’s core features, including variables, data types, control flow, and functions, as well<br> as how to work with essential data structures like lists, dictionaries, and sets.  <br><br>The course is structured into modules, starting with the basics of programming, and gradually <br>moving into more complex topics like object-oriented programming, error handling, and working<br> with external libraries. Additionally, you\'ll learn how to read and write files, handle exceptions, and <br>create reusable code using functions and classes. <br><br> By the end of this course, you\'ll have hands-on experience building Python programs, debugging<br> issues, and integrating third-party libraries. Whether you\'re a complete beginner or looking to <br>enhance your programming skills, this course will give you the practical knowledge needed to start <br>developing Python-based applications and prepare you for more advanced topics like web<br> development, data analysis, and automation.<br>', 'intro_to_programming.jpg', 'https://www.youtube.com/embed/Y8Tko2YC5hA', 'Programming'),
(2, 'Data Science with R', 150, 'Jane Doe', '2024-09-27', '4 Weeks', 'Comprehensive course on using R for data analysis and visualization.', 'This course provides a comprehensive introduction to Data Science using the R programming <br> language. It covers everything from the basics of R programming to more advanced techniques in <br>data manipulation, statistical analysis, and machine learning. You\'ll learn how to clean, process, <br>visualize data, and build predictive models using R\'s rich ecosystem of libraries. <br><br> The course is structured into modules, starting with the fundamentals of R, and progressing towards<br> more complex topics like data visualization with ggplot2, and building machine learning models <br>using caret. By the end of the course, you\'ll be proficient in handling data, performing statistical <br>analysis, and developing machine learning pipelines. <br><br> This course is ideal for beginners in data science as well as those looking to deepen their <br>understanding of data analysis and machine learning using R.<br>.', 'Data_Sience_With_R.jpg', 'https://www.youtube.com/embed/jO3fjjpu4rE', 'AI'),
(3, 'Artificial Intelligence', 500, 'Dr. Sarah Jones', '2024-09-29', '16 Hour', 'Explore AI fundamentals and applications.', 'This course provides an in-depth introduction to Artificial Intelligence (AI), covering the fundamental principles, algorithms, and techniques used in AI today.<br> You will learn about key AI topics, including search algorithms, logic, machine learning, neural networks, and natural language processing, and how to apply them to solve complex problems.<br>  The course is structured into modules that begin with the basic concepts of AI, then progress to advanced topics like deep learning, reinforcement learning, and ethical considerations.<br> By the end of the course, you will be capable of building AI models, understanding their applications, and deploying AI-driven solutions.<br>  This course is ideal for beginners to AI as well as developers and professionals who want to understand the practical applications of artificial intelligence in real-world scenarios.<br>', 'AI.jpg', 'https://www.youtube.com/embed/J4RqCSD--Dg', 'AI'),
(4, 'Web Development', 300, 'John Doe', '2024-09-30', '8 Weeks', 'Learn to build modern web applications.', 'This course provides a comprehensive introduction to Web Development, covering the core technologies and techniques required to build modern, responsive websites and web applications.<br> You will learn key web development skills, including HTML, CSS, and JavaScript for frontend development, as well as server-side programming with technologies like Node.js, Express, and database management using MongoDB or SQL.<br>  The course is structured into modules that start with the basics of website structure and design, then progress into more advanced topics such as responsive design, client-server communication, REST APIs, and deploying web applications.<br> By the end of the course, you will have hands-on experience building full-stack web applications, debugging, and deploying your projects online.<br>  This course is ideal for beginners and developers looking to enhance their skills in web development and gain a deeper understanding of the web development ecosystem.<br>', 'WebDevolepment.jpg', 'https://www.youtube.com/embed/F4fbwKV9dBU', 'Web Development'),
(5, 'Cybersecurity', 450, 'Dr. Emily Smith', '2024-09-25', '16 Weeks', 'Comprehensive course on security protocols.', 'This course provides a comprehensive introduction to Cybersecurity, covering the essential concepts, tools, and techniques used to protect systems, networks, and data from cyber threats.<br> You will learn key cybersecurity topics, including network security, cryptography, ethical hacking, vulnerability assessment, and incident response.<br> The course also explores risk management, security policies, and compliance frameworks that help organizations safeguard their digital assets.<br>  The course is structured into modules that start with the fundamentals of cybersecurity, including basic security principles and common attack vectors, and then progress into more advanced topics like penetration testing, malware analysis, and defense strategies.<br> By the end of the course, you will be capable of identifying potential security vulnerabilities, implementing protective measures, and responding to security incidents.<br>  This course is ideal for beginners and IT professionals looking to strengthen their knowledge of cybersecurity and protect against real-world cyber threats.<br>', 'cybersecurity.jpg', 'https://www.youtube.com/embed/shQEXpUwaIY', 'Cybersecurity'),
(6, 'Data Science', 600, 'Dr. Michael Brown', '2024-09-28', '1 Hour', 'Master data analysis and visualization techniques.', 'This course provides a comprehensive introduction to Data Science, covering essential techniques and tools used to analyze and interpret complex data to drive decision-making.<br> You will learn key data science topics, including data wrangling, exploratory data analysis, statistical modeling, and machine learning.<br> The course also explores data visualization techniques and how to use tools like Python and R to handle and analyze data effectively.<br>  The course is structured into modules that start with the fundamentals of data science, including data collection and cleaning, and progress into more advanced topics like predictive modeling, machine learning algorithms, and data-driven decision-making.<br> By the end of the course, you will have hands-on experience with data analysis, building machine learning models, and presenting your findings in a clear and impactful way.<br>  This course is ideal for beginners and professionals looking to gain practical skills in data science and apply them to real-world problems.<br>', 'DataScience.jpg', 'https://www.youtube.com/embed/X3paOmcrTjQ', 'AI'),
(7, 'Digital Marketing', 350, 'Jessica White', '2024-10-05', '2 Weeks', 'Learn strategies for online marketing success.', 'This course provides a comprehensive introduction to Digital Marketing, covering the essential strategies, tools, and techniques used to create effective online marketing campaigns.<br> You will learn key digital marketing topics, including search engine optimization (SEO), pay-per-click (PPC) advertising, social media marketing, email marketing, and content creation.<br> The course also explores data analytics, marketing automation, and strategies for measuring and optimizing campaign performance.<br>  The course is structured into modules that start with the fundamentals of digital marketing, including building a digital marketing strategy and understanding the digital marketing landscape, and progress into more advanced topics like conversion rate optimization, A/B testing, and leveraging data for decision-making.<br> By the end of the course, you will have hands-on experience creating and managing digital marketing campaigns, analyzing results, and applying best practices to achieve your marketing goals.<br>  This course is ideal for beginners and marketing professionals looking to enhance their digital marketing skills and effectively reach and engage their target audience online.<br>', 'Digital_Marketing.jpg', 'https://www.youtube.com/embed/bixR-KIJKYM', 'Marketing'),
(8, 'Financial Analysis', 400, 'George Lee', '2024-10-06', '2 Weeks', 'Analyze financial statements and trends.', 'This course provides a comprehensive introduction to Financial Analysis, covering the essential tools and techniques used to evaluate financial data and make informed business decisions.<br> You will learn key financial analysis topics, including financial statement analysis, ratio analysis, cash flow analysis, and forecasting techniques.<br> The course also explores valuation methods, budgeting, and risk assessment to help you understand the financial health of a company.<br>  The course is structured into modules that start with the fundamentals of financial accounting, such as understanding balance sheets, income statements, and cash flow statements, and then progress into more advanced topics like discounted cash flow (DCF) analysis, financial modeling, and investment analysis.<br> By the end of the course, you will have hands-on experience performing financial analysis, creating financial models, and interpreting financial data to support decision-making.<br>  This course is ideal for beginners, finance professionals, and business managers looking to strengthen their financial analysis skills and apply them to real-world scenarios.<br>', 'Financial_Analysis.jpg', 'https://www.youtube.com/embed/VxnnVYGGHzo', 'Finance'),
(9, 'Blockchain Technology', 700, 'Dr. William Clark', '2024-10-10', '4 Weeks', 'Understand blockchain and its applications.', 'This course provides a comprehensive introduction to Blockchain Technology, covering the fundamental concepts, technologies, and applications behind blockchain systems.<br> You will learn key topics including the basics of blockchain architecture, consensus mechanisms, cryptographic techniques, and smart contracts.<br> The course also explores various blockchain platforms, such as Ethereum and Hyperledger, and examines real-world applications and use cases across different industries.<br>  The course is structured into modules that start with the foundational principles of blockchain technology, including its history and how it works, and then progress into more advanced topics like decentralized applications (dApps), blockchain security, and scaling solutions.<br> By the end of the course, you will have hands-on experience with blockchain development, understanding of how to create and deploy smart contracts, and insights into the future potential and challenges of blockchain technology.<br>  This course is ideal for beginners and professionals interested in understanding blockchain technology and its applications, and for those looking to leverage blockchain to innovate and solve complex problems in various fields.<br>', 'Blockchain_Technology.jpg', 'https://www.youtube.com/embed/yubzJw0uiE4', 'Blockchain'),
(10, 'UI/UX Design', 450, 'Dr. Alice Green', '2024-10-07', '4 Weeks', 'Design user interfaces with a focus on user experience.', 'This course provides a comprehensive introduction to UI/UX Design, focusing on creating intuitive and aesthetically pleasing user interfaces and experiences.<br> You will learn key UI/UX design topics, including user research, wireframing, prototyping, usability testing, and visual design principles.<br> The course also explores tools and techniques for designing effective user interfaces, such as Adobe XD, Figma, and Sketch, as well as strategies for improving user experience and interaction.<br>  The course is structured into modules that begin with the fundamentals of UI/UX design, including understanding user needs and design thinking, and progress into more advanced topics like responsive design, accessibility, and designing for different devices and platforms.<br> By the end of the course, you will have hands-on experience creating wireframes, prototypes, and high-fidelity designs, as well as conducting usability tests to refine and enhance your designs.<br>  This course is ideal for beginners and professionals looking to develop their skills in UI/UX design and create user-centered designs that provide exceptional user experiences and drive engagement.<br>', 'UI_UX_Design.jpg', 'https://www.youtube.com/embed/55NvZjUZIO8', 'Design'),
(11, 'Advanced Python Programming', 250, 'Dr. Laura Scott', '2024-10-20', '5 Weeks', 'Deep dive into advanced Python features and libraries.', 'This course provides an in-depth exploration of Advanced Python Programming, covering sophisticated techniques and concepts to enhance your Python skills and develop more efficient, robust, and scalable applications.<br> You will learn advanced Python topics, including metaprogramming, decorators, generators, context managers, and concurrent programming.<br> The course also delves into Python’s ecosystem of libraries and frameworks for specialized tasks, such as web development, data analysis, and machine learning.<br>  The course is structured into modules that begin with advanced Python syntax and features, including object-oriented programming and functional programming techniques, and progress into more complex topics like asynchronous programming, design patterns, and testing frameworks.<br> By the end of the course, you will have hands-on experience with advanced Python programming practices, performance optimization, and building scalable applications.<br>  This course is ideal for experienced Python developers looking to deepen their knowledge and expertise, as well as those interested in mastering advanced programming techniques and building sophisticated Python applications.<br>', 'Advanced_Python_Programming.jpg', 'https://www.youtube.com/embed/p15xzjzR9j0', 'Programming'),
(12, 'Machine Learning', 550, 'Dr. Daniel Martinez', '2024-10-19', '8 Weeks', 'Understand machine learning algorithms and their applications.', 'This course provides a comprehensive introduction to Machine Learning, covering fundamental concepts, algorithms, and techniques used to build predictive models and make data-driven decisions.<br> You will learn key machine learning topics, including supervised learning, unsupervised learning, and reinforcement learning, as well as techniques for model evaluation, feature engineering, and hyperparameter tuning.<br> The course also explores popular machine learning frameworks and libraries, such as scikit-learn, TensorFlow, and PyTorch, and applies these tools to real-world problems and datasets.<br>  The course is structured into modules that start with the basics of machine learning, including understanding different types of learning algorithms and their applications, and progress into more advanced topics like deep learning, model deployment, and ethical considerations in machine learning.<br> By the end of the course, you will have hands-on experience building and training machine learning models, evaluating their performance, and deploying them for practical use.<br>  This course is ideal for beginners and professionals looking to develop a solid understanding of machine learning principles and techniques, and apply them to solve complex problems and drive innovation.<br>', 'Machine_Learning.jpg', 'https://www.youtube.com/embed/PeMlggyqz0Y', 'AI'),
(13, 'Basics of C++', 30, 'Osama Elzero', '2024-09-28', '4 Weeks', 'Learn the basics of C++ programming, including syntax, loops, functions, and object-oriented programming.', 'This course provides a comprehensive introduction to Basics of C++, covering the essential concepts and programming techniques needed to develop robust and efficient applications using C++.<br> You will learn key C++ topics, including syntax, data types, control structures, functions, and object-oriented programming principles.<br> The course also explores memory management, file handling, and basic use of the C++ Standard Library.<br>  The course is structured into modules that start with fundamental programming concepts, including basic syntax and data types, and progress into more advanced topics like classes and objects, inheritance, polymorphism, and operator overloading.<br> By the end of the course, you will have hands-on experience writing C++ programs, debugging, and understanding core programming practices and concepts.<br>  This course is ideal for beginners and those new to C++, as well as developers looking to strengthen their understanding of foundational programming concepts and enhance their skills in C++ development.<br>', 'Basics_of_C++.jpg', 'https://www.youtube.com/embed/MNeX4EGtR5Y', 'Programming'),
(14, 'Advanced JavaScript', 300, 'Dr. Alice Williams', '2024-10-15', '4 Weeks', 'Deep dive into advanced JavaScript concepts including ES6, asynchronous programming, and more.', 'This course provides a comprehensive exploration of Advanced JavaScript, covering sophisticated techniques and concepts to enhance your JavaScript programming skills and build more dynamic, efficient, and scalable web applications.<br> You will learn advanced JavaScript topics, including asynchronous programming, advanced functions, and modern JavaScript features introduced in ES6 and beyond.<br> The course also delves into JavaScript frameworks and libraries, such as React, Angular, and Vue.js, and explores advanced topics like performance optimization and design patterns.<br>  The course is structured into modules that begin with advanced JavaScript syntax and concepts, such as closures, promises, and async/await, and progress into more complex topics like functional programming, state management, and building complex web applications.<br> By the end of the course, you will have hands-on experience with advanced JavaScript techniques, understanding of modern JavaScript frameworks, and skills to develop robust and scalable web applications.<br>  This course is ideal for experienced JavaScript developers looking to deepen their knowledge and expertise, as well as those interested in mastering advanced JavaScript techniques and building sophisticated web applications.<br>', 'Advanced_JavaScript.jpg', 'https://www.youtube.com/embed/lkIFF4maKMU', 'Web Development'),
(15, 'Responsive Web Design with Bootstrap', 250, 'Sarah Mitchell', '2024-10-25', '3 Weeks', 'Learn to create responsive web designs using Bootstrap framework.', 'This course provides a comprehensive introduction to Responsive Web Design with Bootstrap, focusing on creating visually appealing and mobile-friendly websites using the Bootstrap framework.<br> You will learn key Bootstrap topics, including the grid system, responsive utilities, components, and custom themes.<br> The course also covers fundamental concepts of responsive design, such as media queries and flexible layouts, and demonstrates how to integrate Bootstrap with other web technologies.<br>  The course is structured into modules that start with the basics of responsive web design and the Bootstrap framework, including setting up your development environment and understanding the grid system, and progress into more advanced topics like creating and customizing components, building complex layouts, and optimizing for different devices.<br> By the end of the course, you will have hands-on experience designing and developing responsive websites using Bootstrap, as well as understanding best practices for creating user-friendly and adaptable web interfaces.<br>  This course is ideal for beginners and web developers looking to enhance their skills in responsive design and utilize Bootstrap to build modern, responsive web applications.<br>', 'Responsive_Web_Design.jpg', 'https://www.youtube.com/embed/yalxT0PEx8c', 'Web Development'),
(16, 'Full Stack Web Development', 600, 'Dr. James Turner', '2024-10-09', '12 Weeks', 'Comprehensive course covering both front-end and back-end web development technologies.', 'This course provides a comprehensive introduction to Full Stack Web Development, covering both frontend and backend technologies required to build complete web applications.<br> You will learn key full stack development topics, including HTML, CSS, and JavaScript for frontend development, as well as server-side programming with technologies like Node.js, Express, and databases such as MongoDB or SQL.<br> The course also explores advanced topics like RESTful APIs, authentication, and deployment strategies.<br>  The course is structured into modules that begin with the fundamentals of web development, including creating and styling web pages and building interactive user interfaces, and progress into more advanced topics like backend development, building APIs, and integrating frontend and backend technologies.<br> By the end of the course, you will have hands-on experience with the entire development lifecycle, from designing user interfaces to deploying a full-stack application, and will be equipped to tackle real-world web development projects.<br>  This course is ideal for beginners and developers looking to become proficient in both frontend and backend development, and to build robust, scalable web applications.<br>', 'Full_Stack_Web_Development.jpg', 'https://www.youtube.com/embed/8KaJRw-rfn8', 'Web Development'),
(17, 'Deep Learning with TensorFlow', 700, 'Dr. Emily Clark', '2024-10-01', '8 Weeks', 'Learn to build and train deep learning models using TensorFlow.', 'This course provides a comprehensive introduction to Deep Learning with TensorFlow, focusing on building and deploying deep learning models using the TensorFlow framework.<br> You will learn key deep learning topics, including neural networks, convolutional neural networks (CNNs), recurrent neural networks (RNNs), and advanced architectures such as transformers.<br> The course also covers essential techniques for model training, evaluation, and optimization, as well as using TensorFlow\'s ecosystem of tools for building scalable and efficient models.<br>  The course is structured into modules that start with the basics of deep learning concepts and the TensorFlow framework, including setting up your development environment and understanding TensorFlow’s core components, and progress into more advanced topics like building and training deep neural networks, implementing transfer learning, and deploying models in production environments.<br> By the end of the course, you will have hands-on experience with deep learning model development using TensorFlow, including data preprocessing, model tuning, and deploying models for real-world applications.<br>', 'Deep_Learning_TensorFlow.jpg', 'https://www.youtube.com/embed/9NsfX9W80rw', 'AI'),
(18, 'Natural Language Processing (NLP)', 550, 'Dr. Michael Johnson', '2024-10-03', '6 Weeks', 'Explore techniques and tools for processing and analyzing human language data.', 'This course provides a comprehensive introduction to Natural Language Processing (NLP), focusing on techniques and tools for analyzing and understanding human language using computational methods.<br> You will learn key NLP topics, including text processing, sentiment analysis, named entity recognition, machine translation, and language generation.<br> The course also explores advanced topics such as word embeddings, transformer models like BERT and GPT, and techniques for building conversational agents and chatbots.<br>  The course is structured into modules that start with the fundamentals of NLP, including text preprocessing and basic algorithms, and progress into more advanced topics like deep learning for NLP, handling large-scale text data, and implementing state-of-the-art NLP models.<br> By the end of the course, you will have hands-on experience with NLP tasks and tools, including building and training models for various natural language understanding and generation tasks, and applying these techniques to real-world problems.<br>  This course is ideal for beginners and professionals looking to develop their skills in NLP and apply machine learning techniques to analyze and interpret human language.<br>', 'NLP.jpg', 'https://www.youtube.com/embed/CMrHM8a3hqw', 'AI'),
(19, 'AI for Business', 400, 'Dr. Lisa Brown', '2024-10-07', '4 Weeks', 'Understand how to leverage AI technologies to drive business decisions and strategies.', 'This course provides a comprehensive introduction to AI for Business, focusing on how artificial intelligence can be leveraged to drive business success and innovation.<br> You will learn key AI topics relevant to business applications, including AI strategy, implementation, and management, as well as specific use cases such as customer insights, automation, and predictive analytics.<br> The course also explores practical aspects of integrating AI into business operations, including data management, model deployment, and evaluating AI solutions.<br>  The course is structured into modules that start with the fundamentals of AI in a business context, including understanding AI technologies and their potential impacts, and progress into more advanced topics like developing an AI strategy, managing AI projects, and measuring ROI.<br> By the end of the course, you will have hands-on experience with implementing AI solutions in business scenarios, understanding how to use AI to solve business problems, and making informed decisions about AI investments.<br>  This course is ideal for business leaders, managers, and professionals looking to understand the strategic benefits of AI and how to apply AI technologies to enhance business performance and drive innovation.<br>', 'AI_for_Business.jpg', 'https://www.youtube.com/embed/UkbVu3fjfpI', 'AI'),
(20, 'Java Programming for Beginners', 250, 'Dr. Linda White', '2024-10-08', '4 Weeks', 'Introduction to Java programming including basic syntax, control flow, and object-oriented principles.', 'This course provides a comprehensive introduction to Java Programming for Beginners, focusing on the foundational concepts and techniques needed to start programming with Java.<br> You will learn key Java topics, including syntax, data types, control structures, object-oriented programming principles, and basic application development.<br> The course also covers essential concepts such as classes, objects, methods, and exception handling, and introduces basic Java development tools and practices.<br>  The course is structured into modules that begin with the basics of Java programming, including understanding the Java programming environment, and progress into more advanced topics like object-oriented programming, working with libraries and APIs, and debugging techniques.<br> By the end of the course, you will have hands-on experience writing, testing, and debugging Java programs, as well as understanding core programming practices and Java concepts.<br>  This course is ideal for beginners with little or no prior programming experience, and those looking to build a strong foundation in Java programming to advance their software development skills.<br>', 'Java_Programming_Beginners.jpg', 'https://www.youtube.com/embed/mAtkPQO1FcA', 'Programming'),
(21, 'C# and .NET Development', 300, 'Dr. Alex Green', '2024-10-05', '6 Weeks', 'Learn C# programming and .NET framework for building robust applications.', 'This course covers everything from the fundamentals of C# programming to more advanced topics in the .NET framework. You\\\'ll learn C# syntax, object-oriented programming, and how to build scalable applications using ASP.NET Core.<br> The course is structured into modules that start from basic concepts and gradually move into complex topics like database integration with Entity Framework and building web applications.<br> By the end of the course, you\\\'ll have hands-on experience with building applications, debugging code, and deploying your own projects. This course is ideal for beginners and those looking to advance their skills in software development.', 'CSharp_NET_Development.jpg', 'https://www.youtube.com/embed/jYjNigSmPE8', 'Programming'),
(22, 'Introduction to Swift Programming', 280, 'Dr. Karen Smith', '2024-10-05', '5 Weeks', 'Learn Swift programming language for developing iOS applications.', 'This course provides a comprehensive introduction to Swift Programming, focusing on the essential concepts and techniques for developing applications using the Swift language.<br> You will learn key Swift topics, including syntax, data types, control flow, functions, and object-oriented programming principles.<br> The course also covers advanced topics such as error handling, optional types, and Swift’s powerful features for modern app development.<br>  The course is structured into modules that start with the basics of Swift programming, including setting up your development environment and understanding Swift’s core syntax, and progress into more advanced topics like working with collections, protocols, and closures.<br> By the end of the course, you will have hands-on experience writing, testing, and debugging Swift code, and will be equipped to develop and deploy iOS applications.<br>  This course is ideal for beginners and those new to Swift who want to build a solid foundation in Swift programming and start developing applications for Apple platforms.<br>', 'Swift_Programming.jpg', 'https://www.youtube.com/embed/nAchMctX4YA', 'Programming'),
(23, 'AI Ethics and Policy', 450, 'Dr. Helen Adams', '2024-10-05', '4 Weeks', 'Understand ethical considerations and policies related to AI.', 'This course provides a comprehensive introduction to AI Ethics and Policy, focusing on the ethical considerations and policy frameworks related to the development and deployment of artificial intelligence technologies.<br> You will learn key topics, including the ethical implications of AI, bias and fairness in AI systems, privacy concerns, and the impact of AI on society.<br> The course also explores regulatory frameworks, policy development, and strategies for responsible AI governance and implementation.<br>  The course is structured into modules that start with foundational ethical principles and issues in AI, including understanding the impact of AI on individuals and communities, and progress into more advanced topics like developing ethical guidelines, creating inclusive policies, and addressing global AI challenges.<br> By the end of the course, you will have a solid understanding of the ethical and policy-related issues in AI, and the skills to contribute to responsible AI development and governance.<br>  This course is ideal for professionals, policymakers, and anyone interested in understanding the ethical and policy dimensions of AI and ensuring that AI technologies are developed and used in a responsible and equitable manner.<br>', 'AI_Ethics.jpg', 'https://www.youtube.com/embed/aGwYtUzMQUk', 'AI'),
(24, 'Robotics and AI', 500, 'Dr. Thomas Harris', '2024-10-05', '6 Weeks', 'Explore the integration of AI in robotics and automation.', 'This course provides a comprehensive introduction to Robotics and AI, focusing on the integration of artificial intelligence with robotics to create intelligent and autonomous systems.<br> You will learn key topics, including robotics fundamentals, AI algorithms, sensor integration, machine learning for robotics, and autonomous navigation.<br> The course also covers advanced topics such as robotics simulation, reinforcement learning for robot control, and real-world applications in industries like manufacturing, healthcare, and autonomous vehicles.<br>  The course is structured into modules that start with the basics of robotics and AI, including understanding robotic systems and AI concepts, and progress into more advanced topics like building and programming robots, using AI for perception and decision-making, and optimizing robot performance.<br> By the end of the course, you will have hands-on experience with designing, programming, and deploying robotic systems integrated with AI, as well as understanding how these technologies can solve complex real-world problems.<br>', 'Robotics_and_AI.jpg', 'https://www.youtube.com/embed/yCXm5cgG0UA', 'AI'),
(25, 'Introduction to Kotlin', 270, 'Dr. Laura Brown', '2024-10-05', '5 Weeks', 'Learn Kotlin programming language for modern Android development.', 'This course provides a comprehensive introduction to Kotlin, focusing on the essential concepts and techniques for developing applications using this modern programming language.<br> You will learn key Kotlin topics, including syntax, data types, control flow, object-oriented programming, and functional programming features.<br> The course also covers advanced features such as null safety, extension functions, and Kotlin’s interoperability with Java.<br>  The course is structured into modules that start with the basics of Kotlin programming, including setting up your development environment and understanding Kotlin’s core syntax, and progress into more advanced topics like creating classes and objects, using functional programming techniques, and integrating Kotlin with existing Java codebases.<br> By the end of the course, you will have hands-on experience writing, testing, and debugging Kotlin code, and be prepared to develop applications for Android or other platforms using Kotlin.<br>  This course is ideal for beginners and those new to Kotlin who want to build a solid foundation in Kotlin programming and start developing modern, efficient applications.<br>', 'Kotlin_Introduction.jpg', 'https://www.youtube.com/embed/xT8oP0wy-A0', 'Programming'),
(26, 'Database Programming with SQL', 320, 'Dr. Brian Smith', '2024-10-23', '6 Weeks', 'Master SQL programming for managing and querying databases.', 'This course provides a comprehensive introduction to Database Programming with SQL, focusing on the essential concepts and techniques needed to interact with relational databases using SQL (Structured Query Language).<br> You will learn key SQL topics, including database design, querying data, creating and managing tables, and performing transactions.<br> The course also covers advanced SQL features such as joins, subqueries, stored procedures, and optimization techniques.<br>  The course is structured into modules that begin with the basics of relational database concepts and SQL syntax, including creating databases and tables, and progress into more advanced topics like complex queries, data manipulation, and database administration.<br> By the end of the course, you will have hands-on experience writing SQL queries, designing and managing databases, and optimizing database performance.<br>  This course is ideal for beginners and professionals looking to develop a strong understanding of database programming and SQL, and to apply these skills in various data management and analysis scenarios.<br>', 'Database_Programming.jpg', 'https://www.youtube.com/embed/zsjvFFKOm3c', 'Programming'),
(27, 'Building Web Applications with React', 350, 'Dr. Emily Davis', '2024-10-24', '6 Weeks', 'Learn to build dynamic web applications using React.', 'This course provides a comprehensive introduction to Building Web Applications with React, focusing on the essential concepts and techniques for developing modern, interactive web applications using the React library.<br> You will learn key React topics, including components, state management, props, hooks, and routing.<br> The course also covers advanced React features such as context API, performance optimization, and integrating React with other libraries and APIs.<br>  The course is structured into modules that start with the basics of React, including setting up your development environment and understanding React’s core concepts, and progress into more advanced topics like managing application state, handling side effects, and building reusable components.<br> By the end of the course, you will have hands-on experience with developing, testing, and deploying React applications, and understanding best practices for creating efficient and scalable web applications.<br>  This course is ideal for beginners and web developers looking to enhance their skills in building dynamic web applications using React, and to understand modern front-end development practices.<br>', 'React_Web_Applications.jpg', 'https://www.youtube.com/embed/gvkqT_Uoahw', 'Web Development'),
(28, 'Introduction to Django', 300, 'Dr. David Clark', '2024-10-27', '5 Weeks', 'Get started with Django for building web applications in Python.', 'This course provides a comprehensive introduction to Django, focusing on the essential concepts and techniques for developing web applications using the Django web framework.<br> You will learn key Django topics, including setting up a Django project, working with models, views, and templates, and implementing user authentication and authorization.<br> The course also covers advanced features such as Django’s ORM (Object-Relational Mapping), form handling, and building RESTful APIs with Django REST Framework.<br>  The course is structured into modules that start with the basics of Django, including setting up your development environment and understanding Django’s core components, and progress into more advanced topics like working with databases, creating custom admin interfaces, and deploying Django applications.<br> By the end of the course, you will have hands-on experience with building, testing, and deploying web applications using Django, and understanding best practices for Django development.<br>  This course is ideal for beginners and developers looking to build robust and scalable web applications using Django, and to understand modern back-end development practices.<br>', 'Django_Introduction.jpg', 'https://www.youtube.com/embed/SIyxjRJ8VNY', 'Web Development'),
(29, 'Introduction to JavaScript', 300, 'Dr. Robert Black', '2024-10-26', '5 Weeks', 'Learn the basics of JavaScript, including syntax, functions, and more.', 'This course provides a comprehensive introduction to JavaScript, focusing on the fundamental concepts and techniques for programming web applications using this versatile language.<br> You will learn key JavaScript topics, including syntax, data types, control structures, functions, and basic DOM (Document Object Model) manipulation.<br> The course also covers essential concepts such as events, error handling, and JavaScript’s role in interactive web development.<br>  The course is structured into modules that begin with the basics of JavaScript programming, including understanding core syntax and basic operations, and progress into more advanced topics like working with objects, arrays, and functions, as well as integrating JavaScript with HTML and CSS.<br> By the end of the course, you will have hands-on experience writing JavaScript code, debugging issues, and building interactive web features.<br>  This course is ideal for beginners with little or no prior programming experience, as well as those looking to build a strong foundation in JavaScript to advance their skills in web development.<br>', 'JavaScript_Basics.jpg', 'https://www.youtube.com/embed/DHjqpvDnNGE', 'Programming'),
(30, 'Advanced CSS Techniques', 350, 'Sarah Brown', '2024-10-25', '6 Weeks', 'Dive deep into advanced CSS techniques for modern web design.', 'ChatGPT This course provides a comprehensive exploration of Advanced CSS Techniques, focusing on advanced styling methods and tools to create visually stunning and responsive web designs.<br> You will learn key CSS topics, including advanced layout techniques, animations, transitions, and custom properties (CSS variables).<br> The course also covers modern CSS features such as Flexbox, CSS Grid, and advanced selectors, as well as techniques for optimizing performance and maintaining consistent design.<br>  The course is structured into modules that start with the basics of advanced CSS features, including Flexbox and CSS Grid layout systems, and progress into more complex topics like creating custom animations, responsive design strategies, and using preprocessors like SASS or LESS.<br> By the end of the course, you will have hands-on experience with advanced CSS techniques, building complex layouts, and optimizing styles for various devices and screen sizes.<br>  This course is ideal for web designers and developers looking to enhance their CSS skills and apply advanced styling techniques to create modern, responsive, and visually appealing web designs.<br>', 'Advanced_CSS.jpg', 'https://www.youtube.com/embed/HZHHBwzmJLk', 'Web Development'),
(31, 'Responsive Web Design with Flexbox', 275, 'Michael Davis', '2024-10-21', '4 Weeks', 'Learn to create responsive web designs using Flexbox.', 'This course provides a comprehensive introduction to Responsive Web Design with Flexbox, focusing on using the Flexbox layout model to create flexible and responsive web designs.<br> You will learn key Flexbox topics, including the Flexbox container and item properties, alignment, spacing, and creating dynamic layouts that adapt to different screen sizes.<br> The course also covers advanced Flexbox techniques, such as nested flex containers, responsive design strategies, and integrating Flexbox with other layout models like CSS Grid.<br>  The course is structured into modules that start with the basics of Flexbox, including understanding the Flexbox model, container and item properties, and creating simple layouts, and progress into more advanced topics like building complex responsive designs, handling different screen sizes, and optimizing performance.<br> By the end of the course, you will have hands-on experience with creating responsive web layouts using Flexbox, understanding best practices for Flexbox implementation, and integrating Flexbox with other CSS techniques.<br>  This course is ideal for web designers and developers looking to master Flexbox and create modern, responsive web designs that work seamlessly across various devices and screen sizes.<br>', 'Flexbox_Design.jpg', 'https://www.youtube.com/embed/K74l26pE4YA', 'Web Development'),
(32, 'Building E-commerce Websites', 400, 'Laura Wilson', '2024-11-05', '8 Weeks', 'Comprehensive course on building fully functional e-commerce websites.', 'This course provides a comprehensive introduction to Building E-commerce Websites, focusing on the essential concepts and techniques needed to create functional and user-friendly online stores.<br> You will learn key topics related to e-commerce website development, including setting up an online store, product management, shopping cart functionality, and payment gateway integration.<br> The course also covers advanced features such as user authentication, order management, and optimizing the user experience for conversions.<br>  The course is structured into modules that start with the basics of e-commerce website development, including choosing an e-commerce platform, designing product pages, and setting up payment methods, and progress into more advanced topics like managing inventory, implementing security measures, and analyzing customer data.<br> By the end of the course, you will have hands-on experience with building and deploying e-commerce websites, understanding best practices for online store design, and optimizing for both user experience and sales.<br>', 'ECommerce_Websites.jpg', 'https://www.youtube.com/embed/9K8FbIKXkbw', 'Web Development');

-- --------------------------------------------------------

--
-- Table structure for table `coursesmembership`
--

CREATE TABLE `coursesmembership` (
  `client` int(11) NOT NULL,
  `course` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `informations`
--

CREATE TABLE `informations` (
  `Client_ID` int(11) NOT NULL,
  `userProfile` varchar(255) NOT NULL,
  `Email` varchar(255) NOT NULL,
  `Username` varchar(255) NOT NULL,
  `Password` varchar(255) NOT NULL,
  `First_Name` varchar(255) DEFAULT NULL,
  `Last_Name` varchar(255) DEFAULT NULL,
  `gender` varchar(6) NOT NULL,
  `Phone_Number` varchar(20) DEFAULT NULL,
  `Country` varchar(100) DEFAULT NULL,
  `University` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `informations`
--

INSERT INTO `informations` (`Client_ID`, `userProfile`, `Email`, `Username`, `Password`, `First_Name`, `Last_Name`, `gender`, `Phone_Number`, `Country`, `University`) VALUES
(25, 'img/prof.webp', 'capoking3@gmail.com', 'Mahmoud2del', 'Pas$w0rd12', 'Mahmoud', 'Adel', 'female', '01015032216', 'Egypt', 'Helwan');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `courses`
--
ALTER TABLE `courses`
  ADD PRIMARY KEY (`Course_ID`),
  ADD UNIQUE KEY `CourseTitle` (`CourseTitle`);

--
-- Indexes for table `coursesmembership`
--
ALTER TABLE `coursesmembership`
  ADD PRIMARY KEY (`client`,`course`),
  ADD KEY `cons_course` (`course`);

--
-- Indexes for table `informations`
--
ALTER TABLE `informations`
  ADD PRIMARY KEY (`Client_ID`),
  ADD UNIQUE KEY `Email` (`Email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `courses`
--
ALTER TABLE `courses`
  MODIFY `Course_ID` int(13) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT for table `informations`
--
ALTER TABLE `informations`
  MODIFY `Client_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `coursesmembership`
--
ALTER TABLE `coursesmembership`
  ADD CONSTRAINT `cons_client` FOREIGN KEY (`client`) REFERENCES `informations` (`Client_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `cons_course` FOREIGN KEY (`course`) REFERENCES `courses` (`Course_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
